### PR TITLE
#2188: CheckFiles jtreg tests fails on legal folder in SapMachine 27

### LINKED ISSUE #2188: CheckFiles jtreg tests fails on legal folder in SapMachine 27
We get the error below because of async-profiler, which is additionally present in SapMachine. So the test needs some adjustments.

```
Checking legal dir subfolder for required files: async
  Found LICENSE
  Missing ADDITIONAL_LICENSE_INFO
----------System.err:(10/515)----------
java.lang.Error: legal dir scan for required files failed
              at CheckFiles.main(CheckFiles.java:198)
              at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
              at java.base/java.lang.reflect.Method.invoke(Method.java:565)
              at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:335)
              at java.base/java.lang.Thread.run(Thread.java:1527)

```

### PR DESCRIPTION
**Pull request by MBaesken**
Handle the async folder of the legal dir differently, it deviates from the normal OpenJDK legal dirs.

fixes #2188

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @MBaesken, this pull request fulfills all formal requirements.

File: test/jdk/build/CheckFiles.java [hunk 1]
```diff
@@ -189,13 +189,18 @@ public static void main(String[] args) throws Exception {
...
-                        for (String fileName : requiredFilesInLegalSubdirs) {
-                            Path filePath = subfolder.resolve(fileName);
-                            if (Files.exists(filePath)) {
-                                System.out.println("  Found " + fileName);
-                            } else {
-                                System.out.println("  Missing " + fileName);
-                                throw new Error("legal dir scan for required files failed");
+                        // SapMachine 2026-02-24: different handling for async profiler subdir we ship with SapMachine
+                        if (subfolder.getFileName().endsWith("async")) {
+                            System.out.println("Skipping async folder from SapMachine, it contains different content from the OJDK legal dirs.");
```
Comment (RealCLanger) [inline test/jdk/build/CheckFiles.java:194]: if you do

`if (subfolder.getFileName().endsWith("async")) {
...
continue
}`

you do not have to change the indentation of the `for (String fileName : requiredFilesInLegalSubdirs) {` block and the diff would be smaller/easier to read, I'd say.

**Review by RealCLanger — CHANGES_REQUESTED** [review]

File: test/jdk/build/CheckFiles.java (hunk 1 above)
Comment (MBaesken) [reply test/jdk/build/CheckFiles.java:194]: True, we can reduce the diff this way .

**Comment by SapMachine** [comment]
Hello @MBaesken, this pull request fulfills all formal requirements.

**Review by RealCLanger — APPROVED** [review]
Looks good now.

**Review by ansteiner — APPROVED** [review]

**Comment by MBaesken** [comment]
Thanks for the reviews !
