### PR TITLE
Increase timeout for slower machines like AIX.

### LINKED ISSUE #2077: FileSocketTransportTest sometimes fails on slow machines
AIX seems to be so slow that the 3 second timeout is sometimes hit. Increase it to 10 max.

### PR DESCRIPTION
**Pull request by schmelter-sap**
Increased the timeout for checking the file socket from 3 to 10 seconds max.

fixes #2077

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @schmelter-sap, this pull request fulfills all formal requirements.

**Review by ArnoZeller — COMMENTED** [review]
Looks good. But can we also throw a JTreg SkippedException in line 103 instead of simply returning.

**Comment by schmelter-sap** [comment]
> Looks good. But can we also throw a JTreg SkippedException in line 103 instead of simply returning.

Done.

**Review by ArnoZeller — APPROVED** [review]
LGTM

**Comment by SapMachine** [comment]
Hello @schmelter-sap, this pull request fulfills all formal requirements.

File: test/jdk/com/sun/jdi/FileSocketTransportTest.java [hunk 1]
```diff
@@ -154,8 +153,16 @@ public static void main(String[] args) throws Throwable {
         }
     }
 
-    private static void checkSocketPresent(String name) {
+    private static void checkSocketPresent(String name) throws Throwable{
```
Comment (RealCLanger) [inline test/jdk/com/sun/jdi/FileSocketTransportTest.java]: could you rather use `throws InterruptedException` (or whatever other checked exception is needed). And there's a blank missing.

**Review by RealCLanger — CHANGES_REQUESTED** [review]
Just a minor thing...

**Review by RealCLanger — APPROVED** [review]
Looks awesome now.

**Comment by SapMachine** [comment]
Hello @schmelter-sap, this pull request fulfills all formal requirements.
