### PR TITLE
SapMachine(11): Compile malloc tracer only for glibc versions < 2.32, and fix tests

### LINKED ISSUE #1482: Enable updated GHA workflow from OpenJDK
In OpenJDK 17, the GHA workflow was updated to embrace a newer linux level. There's some changes needed to enable SapMachine 17 for that.

### PR DESCRIPTION
**Pull request by RealCLanger**
We should cherry-pick the change to compile malloc tracer only for glibc versions < 2.32 to SapMachine 11 as well to cater for the upcoming bump to Ubuntu 22 in GHA. I made a few minor modifications to the changelist from SapMachine 17.

fixes #1482

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

File: test/hotspot/jtreg/runtime/malloctrace/MallocTraceTest.java [hunk 1]
```diff
@@ -59,6 +59,7 @@ public static void main(String... args) throws Throwable {
             ProcessBuilder pb = ProcessTools.createJavaProcessBuilder("-XX:+UnlockDiagnosticVMOptions",
                     option, "-XX:+PrintMallocTraceAtExit", "-version");
             OutputAnalyzer output = new OutputAnalyzer(pb.start());
+            output.reportDiagnosticSummary();
```
Comment (schmelter-sap) [inline test/hotspot/jtreg/runtime/malloctrace/MallocTraceTest.java:62]: Shouldn't be related to this change.

**Review by schmelter-sap — CHANGES_REQUESTED** [review]
Seems to include an unrelated change

**Review by ArnoZeller — APPROVED** [review]
Looks good to me.
I think we should take the not directly related part too. It is useful to get more information in case of an error,

**Review by MBaesken — APPROVED** [review]
Looks okay; I can live with and without the additional reportDiagnosticSummary();

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.
