### PR TITLE
Fix vitals test

### LINKED ISSUE #2088: Failure in VitalsValuesSanityCheck
The test assumes that all committed memory must be in the RSS, which is not true. It should be more lenient.

### PR DESCRIPTION
**Pull request by schmelter-sap**
This makes the test more lenient.

fixes #2088

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @schmelter-sap, this pull request fulfills all formal requirements.

File: test/hotspot/jtreg/runtime/Vitals/VitalsValuesSanityCheck.java [hunk 1]
```diff
@@ -319,8 +319,12 @@ public void run(CommandExecutor executor) {
                 // we should not see mlc > rss
                 if (jvm_nmt_mlc != -1) {
                     if (Platform.isDebugBuild()) {
-                        if (proc_rss_all < jvm_nmt_mlc) {
-                            throw new RuntimeException("NMT mlc higher than RSS?");
+                        // Give a little slack for two reasones:
+                        // - Not all allocated memory has to be in RSS, since some could be swapped out.
+                        // - The peak RSS and peak malloc size are not taken at the exactly same time.
+                        // Both should not lead to a large difference, so we allow a 25 percent deviation.
+                        if (proc_rss_all < jvm_nmt_mlc * 0.8) {
```
Comment (TheRealMDoerr) [inline test/hotspot/jtreg/runtime/Vitals/VitalsValuesSanityCheck.java]: 0.75 would match the comment and message below.

Comment (schmelter-sap) [reply test/hotspot/jtreg/runtime/Vitals/VitalsValuesSanityCheck.java]: No, if the malloc is 25 percent higher than RSS and I multiply by 0.8, then RSS and malloc would be the same.

Comment (TheRealMDoerr) [reply test/hotspot/jtreg/runtime/Vitals/VitalsValuesSanityCheck.java]: Ok, it's clearer in the message below and 1/1.25 = 0.8. The comment above leaves room for different interpretations :-)

**Review by TheRealMDoerr — APPROVED** [review]

File: test/hotspot/jtreg/runtime/Vitals/VitalsValuesSanityCheck.java (hunk 1 above)
Comment (schmelter-sap) [reply test/hotspot/jtreg/runtime/Vitals/VitalsValuesSanityCheck.java]: The code should be clearer now.

**Comment by SapMachine** [comment]
Hello @schmelter-sap, this pull request fulfills all formal requirements.

File: test/hotspot/jtreg/runtime/Vitals/VitalsValuesSanityCheck.java [hunk 2]
```diff
@@ -319,8 +319,12 @@ public void run(CommandExecutor executor) {
                 // we should not see mlc > rss
                 if (jvm_nmt_mlc != -1) {
                     if (Platform.isDebugBuild()) {
-                        if (proc_rss_all < jvm_nmt_mlc) {
-                            throw new RuntimeException("NMT mlc higher than RSS?");
+                        // Give a little slack for two reasones:
```
Comment (RealCLanger) [inline test/hotspot/jtreg/runtime/Vitals/VitalsValuesSanityCheck.java]: Little typo...

```suggestion
                        // Give a little slack for two reasons:
```

**Review by RealCLanger — CHANGES_REQUESTED** [review]
Discovered a little typo

**Comment by SapMachine** [comment]
Hello @schmelter-sap, this pull request fulfills all formal requirements.

**Review by TheRealMDoerr — APPROVED** [review]

File: test/hotspot/jtreg/runtime/Vitals/VitalsValuesSanityCheck.java (hunk 2 above)
Comment (schmelter-sap) [reply test/hotspot/jtreg/runtime/Vitals/VitalsValuesSanityCheck.java]: Fixed

**Comment by SapMachine** [comment]
Hello @schmelter-sap, this pull request fulfills all formal requirements.

**Review by RealCLanger — APPROVED** [review]
