### PR TITLE
Make test for unique stacks more robust

### LINKED ISSUE #1810: Make test for unique stacks more robust
This test fails with an assertion in the profiled VM, caused by the buffer used to store the output requested by jcmd.

### PR DESCRIPTION
**Pull request by schmelter-sap**
This changes the way the stack traces are routed to the test the uniques stacks test, since it produces a big output. We now let the profiled VM print the stacks to stderr and not use the output of jcmd, since the latter is buffered in the profiled VM first and there are hard limits on the maximum size of that buffer,.

fixes #1810

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @schmelter-sap, this pull request fulfills all formal requirements.

File: test/hotspot/jtreg/runtime/malloctrace/MallocHooksTest.java [hunk 1]
```diff
@@ -595,11 +597,25 @@ private static void testUniqueStacks() throws Exception {
                                   "-XX:MallocTraceStackDepth=14").start();
         checkIsAttachable(p);
         p.getInputStream().read();
-        OutputAnalyzer oa = callJcmd(p, "MallocTrace.dump", "-percentage=100");
+        // The output can be large, so dump it directly, since the output of
+        // jcmd is temporary hold in the JVM and there is a limit of 100 MB.
+        final String[] stacks = new String[1];
```
Comment (RealCLanger) [inline test/hotspot/jtreg/runtime/malloctrace/MallocHooksTest.java:602]: Any reason why you are using a String[] here instead of a single String object?

**Review by RealCLanger — COMMENTED** [review]
This change makes sense, I guess. Let's see whether all tests are green.

File: test/hotspot/jtreg/runtime/malloctrace/MallocHooksTest.java (hunk 1 above)
Comment (schmelter-sap) [reply test/hotspot/jtreg/runtime/malloctrace/MallocHooksTest.java:602]: You cannot modify a local variable in an anonymous inner class. So the array trick is the common way.

**Review by RealCLanger — APPROVED** [review]
OK. We should port this fix to upstream, too, I guess?

**Comment by schmelter-sap** [comment]
> OK. We should port this fix to upstream, too, I guess?

If this really fixes the problem in the tests.

**Comment by RealCLanger** [comment]
> > OK. We should port this fix to upstream, too, I guess?
> 
> If this really fixes the problem in the tests.

It should - it looks greenish now. And the error happened on all our ppc64le nodes before.

**Review by MBaesken — APPROVED** [review]
