### PR TITLE
Don't try to resolve CodeBlobs in malloc trace dumps

### LINKED ISSUE #1789: Don't try to resolve CodeBlobs in malloc trace dumps
Since nmethods might get removed or deleted, just using the PC of an old stacktrace could lead to getting the wrong CodeBlob. This is probably more confusing than not having the information at all.

### PR DESCRIPTION
**Pull request by schmelter-sap**
This removes the overoptimistic feature to get the code blob of a PC on the stack when printing stack traces. This could lead to misleading methods being printed, when the blob was moved or deleted in the meantime.

fixes #1789

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @schmelter-sap, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @schmelter-sap, this pull request fulfills all formal requirements.

**Review by reinrich — COMMENTED** [review]
Except for PPC `-XX:+MallocTraceUseBacktrace` is the default. `backtrace()` cannot capture the java part of the stack, can it?

With `-XX:-MallocTraceUseBacktrace` the [frames with a code blobe are excluded](https://github.com/reinrich/SapMachine/blob/00cf7d242f74519b3f33ae050a9bcabbad8fb509/src/hotspot/os/posix/malloctrace/mallocTracePosix.cpp#L861) anyway. Am I correct, and if so: is this a bug or a feature?

**Comment by schmelter-sap** [comment]
The non-backtrace code also stops at the first frame with a code blob associated (due to the fr.cb() != nullptr check in MallocStatisticImpl::capture_stack()).

**Comment by reinrich** [comment]
> The non-backtrace code also stops at the first frame with a code blob associated (due to the fr.cb() != nullptr check in MallocStatisticImpl::capture_stack()).

That's what I meant. I wasn't sure if this was the desired behavior.
So (at most) one frame with an associated code blob is added to the stack trace. Its callers are not added. And that's on purpose. The malloc trace is not meant for analyzing native memory problems originating from java. E.g. leaks where memory is allocated with `Unsafe::allocateMemory` cannot be analyzed, correct?

**Comment by schmelter-sap** [comment]
That's correct. We would see that a memory leak was caused by `Unsafe::allocateMemory`, but would not see the Java code allocating the leaked memory. The same can be said for direct byte buffers.

File: src/hotspot/os/posix/malloctrace/mallocTracePosix.cpp [hunk 1]
```diff
@@ -1843,11 +1838,8 @@ static void print_frame(outputStream* st, address frame) {
   if (os::print_function_and_library_name(st, frame, tmp, sizeof(tmp), true, true, false)) {
     st->cr();
   } else {
-    CodeBlob* blob = CodeCache::find_blob((void*) frame);
-
-    if (blob != nullptr) {
-      st->print_raw(" ");
-      blob->print_value_on(st);
+    if ((frame >= CodeCache::low_bound()) && (frame < CodeCache::high_bound())) {
+      st->print_raw_cr(" <code cache>");
```
Comment (reinrich) [inline src/hotspot/os/posix/malloctrace/mallocTracePosix.cpp:1846]: Please add a short comment why a lookup of the code blob for the pc wouldn't always yield the correct result.

**Review by reinrich — APPROVED** [review]
Looks good to me. A short comment would be nice though.
Thanks, Richard.

**Comment by SapMachine** [comment]
Hello @schmelter-sap, this pull request fulfills all formal requirements.

**Review by reinrich — APPROVED** [review]
Thanks for adding the comment.

**Review by RealCLanger — APPROVED** [review]
